# Generated by Django 4.0.9 on 2023-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ManyToManyField(to='product.album'),
        ),
    ]
